<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1156" started-at="2021-07-30T13:11:57 IST" finished-at="2021-07-30T13:11:58 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1156" started-at="2021-07-30T13:11:57 IST" finished-at="2021-07-30T13:11:58 IST">
      <class name="com.vfislk.openemrtest.ExtentReportDemoTest">
        <test-method status="PASS" signature="start()[pri:0, instance:com.vfislk.openemrtest.ExtentReportDemoTest@401e7803]" name="start" is-config="true" duration-ms="572" started-at="2021-07-30T13:11:57 IST" finished-at="2021-07-30T13:11:57 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.vfislk.openemrtest.ExtentReportDemoTest@401e7803]" name="beforeMethod" is-config="true" duration-ms="16" started-at="2021-07-30T13:11:57 IST" finished-at="2021-07-30T13:11:57 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.vfislk.openemrtest.ExtentReportDemoTest.validTest() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="validTest()[pri:0, instance:com.vfislk.openemrtest.ExtentReportDemoTest@401e7803]" name="validTest" duration-ms="1030" started-at="2021-07-30T13:11:57 IST" finished-at="2021-07-30T13:11:58 IST">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method com.vfislk.openemrtest.ExtentReportDemoTest.validTest() didn't finish within the time-out 1000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.vfislk.openemrtest.ExtentReportDemoTest.validTest() didn't finish within the time-out 1000
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validTest -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.vfislk.openemrtest.ExtentReportDemoTest@401e7803]" name="afterMethod" is-config="true" duration-ms="16" started-at="2021-07-30T13:11:58 IST" finished-at="2021-07-30T13:11:58 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validTest status=FAILURE method=ExtentReportDemoTest.validTest()[pri:0, instance:com.vfislk.openemrtest.ExtentReportDemoTest@401e7803] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="end()[pri:0, instance:com.vfislk.openemrtest.ExtentReportDemoTest@401e7803]" name="end" is-config="true" duration-ms="749" started-at="2021-07-30T13:11:58 IST" finished-at="2021-07-30T13:11:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- com.vfislk.openemrtest.ExtentReportDemoTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
